name: Release BTTInstrumentor

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build universal binary
        run: |
          cd BTTInstrumentor
          swift build -c release --product BTTInstrumentor --triple arm64-apple-macosx
          swift build -c release --product BTTInstrumentor --triple x86_64-apple-macosx
          lipo -create -output BTTInstrumentor \
            .build/arm64-apple-macosx/release/BTTInstrumentor \
            .build/x86_64-apple-macosx/release/BTTInstrumentor
          strip -rSTX BTTInstrumentor

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: BTTInstrumentor/BTTInstrumentor
